In [1]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[7 7 8 8]
 [6 9 9 5]
 [3 8 7 8]]
[[5 3 7]
 [8 7 9]
 [6 9 2]
 [4 3 6]]


In [2]:
a.dot(b)


array([[171, 166, 176],
       [176, 177, 171],
       [153, 152, 155]])